apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saleor-storefront
  namespace: saleor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: saleor-storefront-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: saleor-storefront
            port:
              number: {{ .Values.service.port }}
