image:
  repository: 176899553634.dkr.ecr.us-east-1.amazonaws.com/cloud-native-commerce-platform/saleor-storefront
  tag: "b5c6e605ed3c07eb72571e0d178cc0220670230a"

service:
  port: 3000

ingress:
  host: shop.samadov.xyz

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
